### ISSUE TITLE
Oberon deformed

### ISSUE THREAD

**Issue by Oscariremma** [pap1723/HalfRSS#3]
![oberon](https://cloud.githubusercontent.com/assets/16071372/16422469/c3aab090-3d58-11e6-928d-c41325c7d504.png)
????

**Comment by pap1723** [comment]
What version of the mod are you using? I believe I found this error and fixed it for version 1.1?

**Comment by Oscariremma** [comment]
I used 1.3

**Comment by pap1723** [comment]
Fixed for sure in version 1.5
MAKE SURE YOU DELETE HalfRSS folder out of GameData before you update.
